apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oxhr-authn-server.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "oxhr-authn-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oxhr-authn-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "oxhr-authn-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/app/authn-server", "--config", "/etc/config/config.yaml"]
        ports:
        - name: http
          containerPort: {{ .Values.service.httpTargetPort }}
        - name: grpc
          containerPort: {{ .Values.service.grpcTargetPort }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: config-volume
          mountPath: "/etc/config"
          readOnly: true
        {{- if .Values.volumes.logs.enabled }}
        - name: logs-volume
          mountPath: "/var/log/oxhr"
        {{- end }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.liveness.path }}
            port: http
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readiness.path }}
            port: http
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
      volumes:
      - name: config-volume
        secret:
          secretName: {{ include "oxhr-authn-server.fullname" . }}-config
      {{- if .Values.volumes.logs.enabled }}
      - name: logs-volume
        persistentVolumeClaim:
          claimName: {{ include "oxhr-authn-server.fullname" . }}-logs
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oxhr-authn-server.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "oxhr-authn-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "oxhr-authn-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpTargetPort }}
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcTargetPort }}