version: '3.8'

services:
  geo:
    build:
      context: .
      dockerfile: deployments/docker/geo.Dockerfile
    ports:
      - "8083:8083"
    environment:
      - ENV=dev
    depends_on:
      - postgres
    volumes:
      - ./configs/dev:/app/configs/dev
    networks:
      - semo-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=geo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - semo-network

networks:
  semo-network:
    driver: bridge

volumes:
  postgres_data: