version: '3.8'

services:
  notification:
    build:
      context: .
      dockerfile: deployments/docker/notification.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=dev
    depends_on:
      - postgres
    volumes:
      - ./configs/dev:/app/configs/dev
    networks:
      - semo-network

  api:
    build:
      context: .
      dockerfile: deployments/docker/api.Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ENV=dev
    depends_on:
      - postgres
      - notification
      - auth
    volumes:
      - ./configs/dev:/app/configs/dev
    networks:
      - semo-network

  auth:
    build:
      context: .
      dockerfile: deployments/docker/auth.Dockerfile
    ports:
      - "8082:8082"
    environment:
      - ENV=dev
    depends_on:
      - postgres
    volumes:
      - ./configs/dev:/app/configs/dev
    networks:
      - semo-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=notification_db,api_db,auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create_multiple_dbs.sh:/docker-entrypoint-initdb.d/create_multiple_dbs.sh
    networks:
      - semo-network

networks:
  semo-network:
    driver: bridge

volumes:
  postgres_data: 