apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oxhr-authn-server-logs-pvc
  namespace: oxhr
spec:
  storageClassName: gp2            # EKS 예시. 환경에 따라 스토리지 클래스 변경
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G