apiVersion: v2
name: semo
description: Helm chart for Semo Backend Monorepo
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: api
    version: 0.1.0
    condition: api.enabled
    repository: file://charts/api
  - name: auth
    version: 0.1.0
    condition: auth.enabled
    repository: file://charts/auth
  - name: admin
    version: 0.1.0
    condition: admin.enabled
    repository: file://charts/admin
  - name: worker
    version: 0.1.0
    condition: worker.enabled
    repository: file://charts/worker
