postgres:
  address: ""
  username: ""
  password: ""
  database: ""
  schema: ""

redis:
  addresses: [""]
  username: ""
  password: ""
  database: 0
  tls: false

service:
  service_name: ""
  http_port: 2000
  grpc_port: 2100
  base_url: ""

email:
  smtp_host: ""
  smtp_port: 465
  username: ""
  password: ""
  sender_email: ""

secrets:
  grpc_token: ""
  session_secret: ""
  ecdsa_private_key:
  ecdsa_public_key:

authn:
  session_expire_min: 1440
  access_jwt_expire_min: 5
  refresh_token_expire_min: 43200

logs:
  log_path: ""
  log_level: ""
  stdout_only: true