apiVersion: v1
kind: Secret
metadata:
  name: {{ include "semo-backend-server.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "semo-backend-server.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: |-
    {{ tpl (.Files.Get "config.yaml") . | b64enc }}