postgres:
  address: "postgres:5432"
  username: "dev"
  password: "dev"
  database: "semo"

mongodb:
  uri: "mongodb://localhost:27017"
  username: "dev"
  password: "dev"

redis:
  addresses: ["redis:6379"]
  password: "semoredispassword"

spicedb:
  address: "localhost:50051"
  token: "21fZFvsLHYXfeE9OX5QYrgtIhDZbJlIn"

service:
  service_name: "ox-org-ai-o2297h3l8pe2"
  http_port: 2003
  grpc_port: 2103

organization:
  id: o2297h3l8pe2

email:
  smtp_host: "smtp.daum.net"
  smtp_port: 465
  username: "aground5"
  password: "cjdnuncmntdnpbvk"

secrets:
  grpc_token: "grpc_token"
  jwt_secret: "ZACGCmxOFAiLOJcqNLBGFQRLHvcJbyMT1Lvh6Bh1"
  session_secret: "bGJQ+JZSfe+fuuTO9RQlBT4nH+4vW5cJ"

microservices:
  - name: "ox-authn"
    address: "127.0.0.1"
    http_port: 2000
    grpc_port: 2100
  - name: "ox-geolite"
    address: "127.0.0.1"
    http_port: 2002
    grpc_port: 2102

logs:
  log_path: "/Users/k2zoo/Documents/growingup/ox-hr/authn/app.log"
  log_level: "DEBUG"
  stdout_only: true

s3:
  region: "ap-northeast-2"
  bucket_name: "test-ox-org-o2297h3l8pe2"
  access_key: "AKIA5ZYZPABHMCBNIVNE"
  secret_key: "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"

openai:
  api_key: "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"
  #  api_url: "https://api.openai.com/v1/models"
  #  api_url: "http://localhost:11434/v1/models"
  project_id: "proj_vbJOehMRSRAjqZ0wDS2QFGv1"
  #  base_model: "deepseek-r1:8b"
  xai_api_key: "xai-bYGzbNkUDeqo1KxtZfd3H10tzgVkHoNwotVV8lQNYdogZmLXTK3xXmmwo56sgCLmEtuMXkUJ2we0hjCq"
  gemini_api_key: "AIzaSyAW1fjSUvOXpTh6CeucQv4tiBfX9328YnU"